site_name: K's Bot Documentation
site_url: https://hashimotok-mp.github.io/hashimotok.docs/

# 重要な修正: ドキュメントのソースフォルダを明示的に子ディレクトリに指定
# 💡 リポジトリのルート直下にあるドキュメントファイルを全てこのフォルダに移動してください。
docs_dir: build_docs

theme:
  name: material
  language: ja
  features:
    - navigation.expand
    - content.code.copy

# ナビゲーション (手動で各リポジトリのトップページを登録)
nav:
  - はじめに: index.md
  - Cultivate:
      - トップページ: cultivate/index.md # 親項目の直下に子リストを定義
      - 裏2shot（開発版）: cultivate/system/back_2shot.md
      - 吊下げメッセージ機能: cultivate/system/sticky.md
      - 役職パネル機能: cultivate/system/role_panel.md
      - 設定パネル:
        - 使い方: cultivate/system/setting_panel.md
        - 寝落ち送り機能: cultivate/system/settings/sleep.md
        - BotVC入退室時VC人数変更機能: cultivate/system/settings/bot_vc_limit.md
  - Activate:
  - トップページ: activate/index.md

plugins:
  # ファイル構造が複雑な場合に、目次自動生成などで役立つプラグイン
  - search